# Site settings
title: 201 Games
description: 201 Games Production, Activities, and Many More!!!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 201 Games
user_description: Game Creator
user_title: Mentally Broken Pepol
email: 201.gamedev@gmail.com
twitter_username: lorem_ipsum
github_username:  Fizdan
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
